### ISSUE TITLE
Does this repo still have a purpose?

### ISSUE THREAD

**Issue by diasdavid** [ipld/react-ipld#3]
It probably should be deprecated and archived. @vmx ?

**Comment by vmx** [comment]
@dignifiedquire can we archive this repo?

**Comment by vmx** [comment]
It still has a purpose. Quoting @dignifiedquire:

> It is not invalid, but might be outdated. In an ideal world it would be updated to the latest versions, in reality adding a label to saying that it is not up to date would work, but I don’t think it should be archived. 
Alternative move it to the shipyard.

**Comment by diasdavid** [comment]
That statement doesn't seem to hold truth. There is no need for react-ipld module nor this repo is updated (for 2 years now). Closing the issue and archiving so that it doesn't confuse users.
